[package]
name = "maplibre-native-platform"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
image = { version = "0.25.8", default-features = false, features = ["jpeg", "png", "webp"] }

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
http = "1.4"
threadpool = "1.8.1"

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.21.1", default-features = false }
rustls-platform-verifier = "0.6.2"

[target.'cfg(all(not(target_os = "emscripten"), target_os = "windows"))'.dependencies]
ureq = { version = "3", default-features = false, features = ["native-tls", "gzip", "socks-proxy"] }

[target.'cfg(all(not(target_os = "emscripten"), not(target_os = "windows")))'.dependencies]
ureq = { version = "3", default-features = false, features = ["rustls", "gzip", "platform-verifier", "socks-proxy"] }
