function(mln_configure_render_backend target)
  if(MLN_FFI_RENDER_BACKEND STREQUAL "metal")
    include(render/metal)
    mln_configure_metal_backend(${target})
  elseif(MLN_FFI_RENDER_BACKEND STREQUAL "opengl")
    include(render/opengl)
    mln_configure_opengl_backend(${target})
  elseif(MLN_FFI_RENDER_BACKEND STREQUAL "vulkan")
    include(render/vulkan)
    mln_configure_vulkan_backend(${target})
  elseif(MLN_FFI_RENDER_BACKEND STREQUAL "webgpu")
    include(render/webgpu)
    mln_configure_webgpu_backend(${target})
  else()
    message(FATAL_ERROR "Unsupported render backend: ${MLN_FFI_RENDER_BACKEND}")
  endif()
endfunction()
