function(mln_configure_webgpu_backend target)
  set(MLN_FFI_WEBGPU_SOURCES
      ${PROJECT_SOURCE_DIR}/src/render/webgpu/webgpu_surface_session.cpp
      ${PROJECT_SOURCE_DIR}/src/render/webgpu/webgpu_texture_session.cpp)

  mln_target_project_sources(${target} ${MLN_FFI_WEBGPU_SOURCES})
  target_compile_definitions(${target} PRIVATE MLN_RENDER_BACKEND_WEBGPU=1)

  if(EMSCRIPTEN)
    include(render/emdawnwebgpu)
    mln_configure_emdawnwebgpu(${target})
    if(TARGET mbgl-vendor-webgpu-emdawn)
      mln_configure_emdawnwebgpu(mbgl-vendor-webgpu-emdawn)
      target_link_libraries(${target} PRIVATE mbgl-vendor-webgpu-emdawn)
    endif()
  elseif(MLN_FFI_WEBGPU_IMPL STREQUAL "dawn")
    if(TARGET mbgl-vendor-dawn)
      target_link_libraries(${target} PRIVATE mbgl-vendor-dawn)
    endif()
  elseif(MLN_FFI_WEBGPU_IMPL STREQUAL "wgpu")
    if(TARGET mbgl-vendor-wgpu)
      target_link_libraries(${target} PRIVATE mbgl-vendor-wgpu)
    endif()
  endif()
endfunction()
